development:
  url: "http://discourse-dev.networkofinnovators.org"
  api_key: "1aab33514000d1660d4d183d5df90a566a84e553a7aef7046a47bc007a88e37f"
  api_username: "david"

production:
  url: "http://discourse-dev.networkofinnovators.org"
  api_key: "1aab33514000d1660d4d183d5df90a566a84e553a7aef7046a47bc007a88e37f"
  api_username: "david"